name: redux_api_middleware
author: Carlos Lira <carloshenriquen.lira@gmail.com>
description: A dart redux middleware for calling APIs. APIs interact with reducers made easy..
homepage: https://github.com/carloslira/redux_api_middleware
version: 0.1.9

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  meta: ">=1.0.0 <2.0.0"
  redux: ">=4.0.0 <5.0.0"
  http: ^0.12.0
